Search and Filtering Projects
abbiehuynh/my-crochet-corner pull request #9
Opened 2024-10-30 20:44 UTC by abbiehuynh

## This PR includes:
- **Implementing a search bar to allow users to search through list of projects by project name**
- **Adding buttons for sorting projects to allow users to view projects by name, type, and date**
  - Name: Sorts projects alphabetically by project name
  - Status: Sorts projects based on their project type (Amigurimi, Blanket, Clothing, Etc)
  - Date: Sorts projects by their last updated date with the most recent updates appearing first
- **Adding buttons for filtering projects to allow users to view projects by project status - All projects, To Do, In Progress, and Completed**
  - All Projects: Displays all projects regardless of status
  - To Do: Displays only projects that are to be worked on.
  - In Progress: Displays projects that are currently being worked on.
  - Completed: Displays projects that have been finished. 
- Users can apply sort and filter buttons with the search results to provide specific results
- **Applying dynamic headers for sorting and filtering buttons to show users what results are being displayed**
- Functions for search and sorting are located in the Project Provider to allow these functions to be reusable in other areas of the app such as the Favorites Page. 

## Changes:
**Before: Homepage**
![home-page-before-pr9](https://github.com/user-attachments/assets/905fcdb8-dd6a-47ab-96fd-3c739598b5e0)

**After: Adding Search bar, buttons, and dynamic headers**

https://github.com/user-attachments/assets/5f7f766a-fc4a-4b2b-a460-5a190fbdd39d

### Notes: 
- Please review the app structure and suggest any improvements for the logic of the search and sort functions located in the ProjectProvider Context.

---
Merging search-projects branch into projects branch.

2024-10-30 22:04 UTC, davidmedina-contact requested changes

2024-10-30 22:04 UTC, davidmedina-contact commented on client/src/components/home/ProjectProvider.jsx
> +        const matchesCategory = selectedCategory === 'All' || project.project_status === selectedCategory;
Might be better to define a constant for 'All' that can be reused elsewhere

2024-10-30 22:04 UTC, davidmedina-contact commented on client/src/components/home/ProjectProvider.jsx
> +        const matchesSearch = project.project_name.toLowerCase().includes(searchQuery.toLowerCase());
There might be some sanitizing to the search query you might want to consider, like removing trailing and starting blank spaces, any malicious characters that could be an SQL injection risk, etc

2024-10-30 22:04 UTC, davidmedina-contact commented on client/src/components/home/ProjectProvider.jsx
> +        }
This should be a [switch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch)

2024-10-30 22:04 UTC, davidmedina-contact commented on client/src/components/home/ProjectProvider.jsx
> +    }}>
Is the project context provider becoming too big? For testing purposes, this might become more complex down the road

2024-10-30 22:04 UTC, davidmedina-contact commented on client/src/components/home/SortProjectStatus.jsx
> +    const [sortHeader, setSortHeader] = useState('Sort projects by criteria');
These strings might be better defined in localized stirng constants for future proofing

2024-10-30 22:27 UTC, abbiehuynh commented on client/src/components/home/ProjectProvider.jsx
> +    }}>
Hmm, should I create another context provider to manage the sort and filtering to make this one more manageable?

2024-10-30 22:40 UTC, abbiehuynh commented on client/src/components/home/ProjectProvider.jsx
> +        }
Submitted changes with commit: [0128ca2](https://github.com/abbiehuynh/my-crochet-corner/pull/9/commits/0128ca2d346441242602c60079c6ba8323894b71)

2024-10-30 23:25 UTC, abbiehuynh commented on client/src/components/home/SortProjectStatus.jsx
> +    const [sortHeader, setSortHeader] = useState('Sort projects by criteria');
Submitted changes with commit: [6a62a0e](https://github.com/abbiehuynh/my-crochet-corner/pull/9/commits/6a62a0e7f4f2fd48d72ffbf723282621547db66b)

2024-10-30 23:45 UTC, abbiehuynh commented on client/src/components/home/ProjectProvider.jsx
> +        const matchesSearch = project.project_name.toLowerCase().includes(searchQuery.toLowerCase());
I added a function to sanitize the search query that could be a SQL risk, such as removing leading and trailing spaces, escaping single and double quotes, removing semicolons and comment sequences, as well as including case insensitivity. 

Submitted changes with commit: [729d09a](https://github.com/abbiehuynh/my-crochet-corner/pull/9/commits/729d09aa3d54c188b6e6c90ef728a0993a6c5805)

2024-10-30 23:46 UTC, abbiehuynh commented on client/src/components/home/ProjectProvider.jsx
> +        const matchesCategory = selectedCategory === 'All' || project.project_status === selectedCategory;
Submitted changes with commit: [729d09a](https://github.com/abbiehuynh/my-crochet-corner/pull/9/commits/729d09aa3d54c188b6e6c90ef728a0993a6c5805)

2024-10-31 00:01 UTC, davidmedina-contact commented on client/src/components/home/ProjectProvider.jsx
> +    }}>
Might be worth a thought once you start testing

2024-10-31 00:03 UTC, davidmedina-contact commented
LGTM

2024-10-31 00:03 UTC, davidmedina-contact approved these changes

2024-10-31 05:47 UTC, Maithanhceu approved these changes
This is looks good! Good job on adding the Aria-label to make the site more accessible for screen-readers

2024-10-31 05:47 UTC, Maithanhceu commented on client/src/components/home/SearchBar.jsx
> +            aria-label="Search"
Love this use of the aria-label

2024-10-31 15:35 UTC, merged